name: selfmanagement_app
description: "A modular self-management application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  
  # State Management
  flutter_riverpod: ^2.6.1
  
  # Local database
  sqflite: ^2.4.1
  
  # Path Provider
  path: ^1.9.0
  
  # UUID
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true